#jassnet-like implementation

SR = 4000
SEG_SECONDS = 2.0
SEG_SAMPLES = int(SR * SEG_SECONDS)
KERNEL_SIZE = 16
STRIDE = KERNEL_SIZE // 2
LATENT_FRAME_MS = STRIDE / SR * 1000.0


JASSNET_DIM = 64
N_FILTERS = JASSNET_DIM
N_LATENT = JASSNET_DIM
N_SOURCES = 2
JASSNET_NUM_MODULES = 8
JASSNET_EXPANSION = 2
JASSNET_ATTN_DIM = 32
JASSNET_LOCAL_CHUNK = 50
JASSNET_CONV_KERNEL = 3
JASSNET_RPE_KERNEL = 3
JASSNET_POSITIONAL_ENCODING = True
DROPOUT_P = 0.1


#NO Multiscale-depthwise convolution in encoding or decoding, no dilations
ENCODER_R = 0
DECODER_R = 0
DILATIONS = ()

SEP_N_STACKS = 1
SEP_BLOCKS_PER_STACK = JASSNET_NUM_MODULES
SEP_TCN_BOTTLENECK = JASSNET_ATTN_DIM

ATTN_HEADS = 1
ATTN_WINDOW = JASSNET_LOCAL_CHUNK
N_GLOBAL_TOKENS = 0
MASK_SCALE = "ReLU_unbounded"


PROJECT_ROOT = "/nas/home/pcallandrone/DeepLearning"

PSEUDO_DIR = None
SUPERVISED_DIR = PROJECT_ROOT + "/dataset/processed/torabi_full_40x40_10x10_no_unused_fold2"
SYNTH_SUPERVISED_DIR = SUPERVISED_DIR

EXPERIMENT_NAME = "12072026_jassnet_8modules_TORABI"
CKPT_DIR = PROJECT_ROOT + "/outputs/checkpoints/" + EXPERIMENT_NAME
RESULTS_DIR = PROJECT_ROOT + "/outputs/results/" + EXPERIMENT_NAME

PRETRAIN_CKPT = None
EVAL_CKPT = None
STAGE = "supervised_from_scratch"
EVALUATE_POST_TRAINING = True

USE_SOURCE_DISJOINT_SPLIT = True
SOURCE_DISJOINT_SPLIT_CSV = SUPERVISED_DIR + "/source_disjoint_split_smoke.csv"

TARGET_GAIN_MODE = "none"
TARGET_GAIN_H = 1.0
TARGET_GAIN_L = 1.0
TARGET_GAIN_REMOVE_DC = True
USE_BASE_TRIPLET_ALLOWLIST = False
BASE_TRIPLET_ALLOWLIST = ()
BASE_TRIPLET_DENYLIST = ()

AUGMENT_TRAINING = False
MIXED_TRAINING = False



FILTER_LOCAL_SNR = False
LOCAL_SNR_THRESHOLD_DB = 20.0
LOCAL_SNR_ANALYSIS_CSV = (
    PROJECT_ROOT
    + "/outputs/results/SNR_IMBALANCE_RUNS/full_dataset_local_snr_amplitude_analysis/"
    "all_segments_amplitude_snr.csv"
)

APPLY_MIXTURE_POLARITY_CALIBRATION = False
APPLY_MIXTURE_GAIN_CALIBRATION = False

LAMBDA_RMS = 1.0
LAMBDA_POLARITY = 0.0
LAMBDA_MIX = 0.0
LAMBDA_L1 = 0.1
LAMBDA_MIX_POLARITY = 0.0

LOSS_WEIGHT_H = 1.0
LOSS_WEIGHT_L = 1.0

USE_DYNAMIC_SOURCE_WEIGHTS = False

BATCH_SIZE = 64
NUM_WORKERS = 4
WEIGHT_DECAY = 1e-5
GRAD_CLIP = 5.0

PRETRAIN_EPOCHS = 10
PRETRAIN_LR = 1e-3
PRETRAIN_PATIENCE = 4

FINETUNE_EPOCHS = 15
FINETUNE_PATIENCE = 3
WARMUP_EPOCHS = 1
FINETUNE_LR = 5e-4

FINETUNE_MODE = "full"
TWO_STAGE_SEPARATOR_EPOCHS = 0
SEPARATOR_FINETUNE_LR = 2e-5
FULL_FINETUNE_LR = 2e-5


USE_SNR_SAMPLE_WEIGHTS = False
USE_V1_RESYNTH_TRAIN_INJECTION = False


ONLY_FOLD = 1
SMOKE_MAX_BASE_TRIPLETS = None
N_FOLDS = 1
SEED = 42
MODEL_SEED = 42

#Same parameters deeper run-> Torabi Fold2 8 modules
